pipeline {
    agent any
    parameters {
        string(name: 'TEST_PROJECT_PATH', defaultValue: 'Api/TestController/TestController.csproj')
        string(name: 'API_SOLUTION', defaultValue: 'Api/Api.sln')
    }
    stages {
        stage('Build') {
            steps{
        powershell '''
            dotnet restore $($env:API_SOLUTION) --source https://api.nuget.org/v3/index.json
            dotnet build $($env:API_SOLUTION) -p:Configuration=release -v:n
            dotnet test $($env:TEST_PROJECT_PATH)
            dotnet publish $($env:API_SOLUTION) -c Release
            compress-archive Api/Api/bin/Release/netcoreapp2.2/publish artifact.zip -Update
        '''}
        }
        stage('Deploy') {
            steps{
            powershell '''
            expand-archive artifact.zip ./ -Force
            dotnet publish/WebApplicationApi.dll  
            '''
            }
        }
    }
}